FROM public.ecr.aws/lambda/python:3.12-slim

# For real-time logging
ENV PYTHONUNBUFFERED=1

WORKDIR ${LAMBDA_TASK_ROOT}

# Install system dependencies for curl_cffi
RUN apt-get update && apt-get install -y gcc

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ebuyer_scraper.py lambda_handler.py ./

CMD ["lambda_handler.lambda_handler"]
