FROM python:3.12-slim

# For real-time logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies for curl_cffi
RUN apt-get update && apt-get install -y gcc

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY awd_it_scraper.py .

CMD ["awd_it_scraper.handler"]
